import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1779000000000 implements MigrationInterface {
    name = 'InitialSchema1779000000000'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`activity_types\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, \`deletedAt\` timestamp(6) NULL, \`name\` varchar(100) NOT NULL, \`code\` varchar(50) NOT NULL, \`autoGradable\` tinyint NOT NULL DEFAULT 1, \`baseWeight\` float NOT NULL DEFAULT '1', \`configSchema\` json NULL, UNIQUE INDEX \`IDX_ce7823da2e27674fbd0392e867\` (\`code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`activities\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, \`deletedAt\` timestamp(6) NULL, \`learningUnitId\` int NOT NULL, \`activityTypeId\` int NOT NULL, \`createdBy\` int NOT NULL, \`title\` varchar(200) NOT NULL, \`description\` text NULL, \`difficulty\` enum ('basico', 'intermedio', 'avanzado') NOT NULL DEFAULT 'basico', \`totalPoints\` int NOT NULL DEFAULT '100', \`passingScore\` int NOT NULL DEFAULT '60', \`attemptsAllowed\` int NOT NULL DEFAULT '3', \`timeLimit\` int NULL, \`order\` int NOT NULL DEFAULT '0', \`status\` enum ('draft', 'review', 'published', 'archived') NOT NULL DEFAULT 'draft', \`isRequired\` tinyint NOT NULL DEFAULT 0, \`adaptiveWeight\` float NOT NULL DEFAULT '1', \`publishedAt\` timestamp NULL, INDEX \`IDX_bd3144edc073063648e4efbb1f\` (\`learningUnitId\`, \`status\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`contents\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, \`deletedAt\` timestamp(6) NULL, \`learningUnitId\` int NOT NULL, \`title\` varchar(255) NOT NULL, \`type\` enum ('video', 'markdown', 'code', 'pdf', 'image') NOT NULL, \`body\` longtext NULL, \`metadata\` json NULL, \`order\` int NOT NULL DEFAULT '0', \`isVisible\` tinyint NOT NULL DEFAULT 1, INDEX \`IDX_58754b2430201454bffc79cec6\` (\`learningUnitId\`, \`order\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`learning_units\` (\`id\` int NOT NULL AUTO_INCREMENT, \`title\` varchar(255) NOT NULL, \`description\` text NULL, \`difficulty\` enum ('basico', 'intermedio', 'avanzado') NOT NULL DEFAULT 'basico', \`order\` int NOT NULL DEFAULT '0', \`isActive\` tinyint NOT NULL DEFAULT 1, \`topicId\` int NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`topics\` (\`id\` int NOT NULL AUTO_INCREMENT, \`title\` varchar(255) NOT NULL, \`description\` text NULL, \`order\` int NOT NULL DEFAULT '0', \`isActive\` tinyint NOT NULL DEFAULT 1, \`sectionId\` int NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sections\` (\`id\` int NOT NULL AUTO_INCREMENT, \`title\` varchar(255) NOT NULL, \`description\` text NULL, \`order\` int NOT NULL DEFAULT '0', \`isPublished\` tinyint NOT NULL DEFAULT 0, \`classId\` int NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_f0881122b5efd7b004f082c084\` (\`classId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`classes\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`description\` text NULL, \`code\` varchar(255) NOT NULL, \`teacherId\` int NOT NULL, \`isActive\` tinyint NOT NULL DEFAULT 1, \`startDate\` date NULL, \`endDate\` date NULL, \`maxStudents\` int NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_4b7ac7a7eb91f3e04229c7c0b6\` (\`teacherId\`), UNIQUE INDEX \`IDX_cf7491878e0fca859943862998\` (\`code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`enrollments\` (\`id\` varchar(36) NOT NULL, \`classId\` int NOT NULL, \`studentId\` int NOT NULL, \`status\` enum ('active', 'inactive', 'withdrawn', 'completed') NOT NULL DEFAULT 'active', \`joined_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`left_at\` timestamp NULL, \`last_activity_at\` timestamp NULL, UNIQUE INDEX \`IDX_43599c2329cb145ee8ba57079b\` (\`classId\`, \`studentId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`institutions\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, UNIQUE INDEX \`IDX_15c98649276025998cd1acaf61\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`programs\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`maxSemesters\` int NOT NULL, \`institutionId\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_affiliations\` (\`id\` int NOT NULL AUTO_INCREMENT, \`userId\` int NOT NULL, \`programId\` int NOT NULL, \`roleType\` varchar(255) NOT NULL, \`currentSemester\` int NULL, \`isActive\` tinyint NOT NULL DEFAULT 1, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` int NOT NULL AUTO_INCREMENT, \`email\` varchar(255) NOT NULL, \`password\` varchar(255) NOT NULL, \`fullName\` varchar(255) NOT NULL, \`role\` enum ('admin', 'docente', 'estudiante') NOT NULL DEFAULT 'estudiante', \`isActive\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` timestamp(6) NULL, UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tutor_conversations\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, \`deletedAt\` timestamp(6) NULL, \`studentId\` int NOT NULL, \`role\` varchar(50) NOT NULL, \`content\` text NOT NULL, \`metadata\` json NULL, INDEX \`IDX_56c5533282e9ec141a9369081c\` (\`studentId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`activity_questions\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, \`deletedAt\` timestamp(6) NULL, \`activityId\` int NOT NULL, \`type\` enum ('mcq', 'coding', 'drag_drop', 'matching', 'fill_code', 'ordering', 'ai_evaluated') NOT NULL, \`question\` text NOT NULL, \`points\` int NOT NULL DEFAULT '10', \`order\` int NOT NULL DEFAULT '0', \`config\` json NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`submission_answers\` (\`id\` int NOT NULL AUTO_INCREMENT, \`submissionId\` varchar(255) NOT NULL, \`questionId\` int NOT NULL, \`answer\` json NOT NULL, \`isCorrect\` tinyint NULL, \`score\` float NOT NULL DEFAULT '0', \`feedback\` text NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`submissions\` (\`id\` varchar(36) NOT NULL, \`activityId\` int NOT NULL, \`studentId\` int NOT NULL, \`score\` float NOT NULL DEFAULT '0', \`feedback\` text NULL, \`attemptNumber\` int NOT NULL DEFAULT '1', \`status\` enum ('in_progress', 'submitted', 'graded', 'expired') NOT NULL DEFAULT 'in_progress', \`startedAt\` timestamp NULL, \`submittedAt\` timestamp NULL, \`timeSpentSeconds\` int NOT NULL DEFAULT '0', \`lastSavedAt\` timestamp NULL, \`autosaveData\` json NULL, \`isAbandoned\` tinyint NOT NULL DEFAULT 0, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, \`deletedAt\` timestamp(6) NULL, INDEX \`IDX_a3a94d0cb86c82e1f221100a44\` (\`studentId\`, \`status\`), INDEX \`IDX_03e1c1ddb6b33421fe8935a73f\` (\`studentId\`, \`activityId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`review_schedules\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, \`deletedAt\` timestamp(6) NULL, \`studentId\` int NOT NULL, \`learningUnitId\` int NOT NULL, \`nextReviewDate\` timestamp NOT NULL, \`urgencyLevel\` int NOT NULL DEFAULT '0', \`intervalDays\` int NOT NULL DEFAULT '1', \`repetitions\` int NOT NULL DEFAULT '0', \`lastReviewedAt\` timestamp NULL, UNIQUE INDEX \`IDX_7e969b53fac069d54b248bf537\` (\`studentId\`, \`learningUnitId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`bank_questions\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, \`deletedAt\` timestamp(6) NULL, \`bankId\` int NOT NULL, \`type\` enum ('mcq', 'coding', 'drag_drop', 'matching', 'fill_code', 'ordering', 'ai_evaluated') NOT NULL, \`question\` text NOT NULL, \`config\` json NOT NULL, \`tags\` text NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`question_banks\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, \`deletedAt\` timestamp(6) NULL, \`name\` varchar(255) NOT NULL, \`description\` text NULL, \`authorId\` int NOT NULL, \`isPublic\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`prerequisites\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, \`deletedAt\` timestamp(6) NULL, \`targetUnitId\` int NOT NULL, \`requiredUnitId\` int NOT NULL, \`minMasteryRequired\` float NOT NULL DEFAULT '60', UNIQUE INDEX \`IDX_e55545b98f91f6a5da8b004833\` (\`targetUnitId\`, \`requiredUnitId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`notifications\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, \`deletedAt\` timestamp(6) NULL, \`userId\` int NOT NULL, \`title\` varchar(255) NOT NULL, \`message\` text NOT NULL, \`isRead\` tinyint NOT NULL DEFAULT 0, \`type\` enum ('grade', 'review_schedule', 'info') NOT NULL DEFAULT 'info', PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`messages\` (\`id\` int NOT NULL AUTO_INCREMENT, \`senderId\` int NOT NULL, \`receiverId\` int NOT NULL, \`content\` text NOT NULL, \`isRead\` tinyint NOT NULL DEFAULT 0, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`learning_progress\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, \`deletedAt\` timestamp(6) NULL, \`studentId\` int NOT NULL, \`learningUnitId\` int NOT NULL, \`mastery\` float NOT NULL DEFAULT '0', \`status\` enum ('no_visto', 'explorado', 'en_practica', 'comprension_parcial', 'dominado') NOT NULL DEFAULT 'no_visto', \`priority\` int NOT NULL DEFAULT '0', \`successRate\` float NOT NULL DEFAULT '0', \`attemptsCount\` int NOT NULL DEFAULT '0', \`completedActivities\` int NOT NULL DEFAULT '0', \`lastActivityId\` int NULL, UNIQUE INDEX \`IDX_21d1790565894696c13f099ce9\` (\`studentId\`, \`learningUnitId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`execution_results\` (\`id\` varchar(36) NOT NULL, \`submissionAnswerId\` int NOT NULL, \`status\` varchar(50) NOT NULL, \`stdout\` text NULL, \`stderr\` text NULL, \`executionTimeMs\` int NOT NULL DEFAULT '0', \`memoryUsedKB\` int NOT NULL DEFAULT '0', \`testCaseLabel\` varchar(255) NULL, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, \`deletedAt\` timestamp(6) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`achievements\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP, \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, \`deletedAt\` timestamp(6) NULL, \`name\` varchar(255) NOT NULL, \`description\` text NULL, \`iconUrl\` varchar(255) NOT NULL, \`points\` int NOT NULL DEFAULT '10', \`unlockedById\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`activity_logs\` (\`id\` varchar(36) NOT NULL, \`studentId\` int NOT NULL, \`action\` enum ('content_read', 'activity_started', 'submission_graded', 'unit_completed') NOT NULL, \`referenceId\` varchar(100) NOT NULL, \`referenceType\` varchar(50) NOT NULL, \`metadata\` json NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_78666521e99d2bbe69f2ea830a\` (\`referenceId\`, \`action\`), INDEX \`IDX_8befb5d0b0f799f6b6a1af46b5\` (\`studentId\`, \`action\`), INDEX \`IDX_0239ac3be75a977a71ae9cf8e0\` (\`studentId\`, \`createdAt\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`activities\` ADD CONSTRAINT \`FK_cc686d463a463786129e1de1cea\` FOREIGN KEY (\`learningUnitId\`) REFERENCES \`learning_units\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`activities\` ADD CONSTRAINT \`FK_3689e28651a4b078af91952bed8\` FOREIGN KEY (\`activityTypeId\`) REFERENCES \`activity_types\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`activities\` ADD CONSTRAINT \`FK_dc4b610a410beaee2dca89e7536\` FOREIGN KEY (\`createdBy\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`contents\` ADD CONSTRAINT \`FK_03bf08d52358f58f07787fc6b8f\` FOREIGN KEY (\`learningUnitId\`) REFERENCES \`learning_units\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`learning_units\` ADD CONSTRAINT \`FK_cb4ada233555d57c4f6e50609ad\` FOREIGN KEY (\`topicId\`) REFERENCES \`topics\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`topics\` ADD CONSTRAINT \`FK_36089054397b6db8da2fd67a073\` FOREIGN KEY (\`sectionId\`) REFERENCES \`sections\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sections\` ADD CONSTRAINT \`FK_f0881122b5efd7b004f082c084c\` FOREIGN KEY (\`classId\`) REFERENCES \`classes\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`classes\` ADD CONSTRAINT \`FK_4b7ac7a7eb91f3e04229c7c0b6f\` FOREIGN KEY (\`teacherId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`enrollments\` ADD CONSTRAINT \`FK_470304681bce2933d3cbb680db8\` FOREIGN KEY (\`classId\`) REFERENCES \`classes\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`enrollments\` ADD CONSTRAINT \`FK_bf3ba3dfa95e2df7388eb4589fd\` FOREIGN KEY (\`studentId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`programs\` ADD CONSTRAINT \`FK_82f9404fa3d1a3e1cc2c8f2d22a\` FOREIGN KEY (\`institutionId\`) REFERENCES \`institutions\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_affiliations\` ADD CONSTRAINT \`FK_be5b7060fa1c8a8ba2a8504e746\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_affiliations\` ADD CONSTRAINT \`FK_f6200ccffc5064f1be2e329a245\` FOREIGN KEY (\`programId\`) REFERENCES \`programs\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`tutor_conversations\` ADD CONSTRAINT \`FK_56c5533282e9ec141a9369081ca\` FOREIGN KEY (\`studentId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`activity_questions\` ADD CONSTRAINT \`FK_a20191ae2559a453d0bba75da9b\` FOREIGN KEY (\`activityId\`) REFERENCES \`activities\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`submission_answers\` ADD CONSTRAINT \`FK_7e0d6cf6173772c12089cf97474\` FOREIGN KEY (\`submissionId\`) REFERENCES \`submissions\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`submission_answers\` ADD CONSTRAINT \`FK_49b240a1fb2de5d9308d2125597\` FOREIGN KEY (\`questionId\`) REFERENCES \`activity_questions\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`submissions\` ADD CONSTRAINT \`FK_5ddeb5fb4f6c38b0439ec52bff2\` FOREIGN KEY (\`activityId\`) REFERENCES \`activities\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`submissions\` ADD CONSTRAINT \`FK_4fc99318a291abd7e2a50f50851\` FOREIGN KEY (\`studentId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`review_schedules\` ADD CONSTRAINT \`FK_c76dfbe4d695e9eb548d0826c7e\` FOREIGN KEY (\`studentId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`review_schedules\` ADD CONSTRAINT \`FK_bc8f68cc5d9a235438a767fd5a0\` FOREIGN KEY (\`learningUnitId\`) REFERENCES \`learning_units\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bank_questions\` ADD CONSTRAINT \`FK_916010c09855614e142d71f72a2\` FOREIGN KEY (\`bankId\`) REFERENCES \`question_banks\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`question_banks\` ADD CONSTRAINT \`FK_6f408c9e6d742703af93a98083f\` FOREIGN KEY (\`authorId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`prerequisites\` ADD CONSTRAINT \`FK_f205de314c224ec276293924105\` FOREIGN KEY (\`targetUnitId\`) REFERENCES \`learning_units\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`prerequisites\` ADD CONSTRAINT \`FK_b616443e090e940951cc2fbaf94\` FOREIGN KEY (\`requiredUnitId\`) REFERENCES \`learning_units\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`FK_692a909ee0fa9383e7859f9b406\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD CONSTRAINT \`FK_2db9cf2b3ca111742793f6c37ce\` FOREIGN KEY (\`senderId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`messages\` ADD CONSTRAINT \`FK_acf951a58e3b9611dd96ce89042\` FOREIGN KEY (\`receiverId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`learning_progress\` ADD CONSTRAINT \`FK_ff1936e29305b9f0e52eb1fde30\` FOREIGN KEY (\`studentId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`learning_progress\` ADD CONSTRAINT \`FK_2d86a96d67fe2848ec0d39560ba\` FOREIGN KEY (\`learningUnitId\`) REFERENCES \`learning_units\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`learning_progress\` ADD CONSTRAINT \`FK_c4ba35959dbdc57dde97ceb7473\` FOREIGN KEY (\`lastActivityId\`) REFERENCES \`activities\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`execution_results\` ADD CONSTRAINT \`FK_35b26782b11673f9510ecf7a69e\` FOREIGN KEY (\`submissionAnswerId\`) REFERENCES \`submission_answers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`achievements\` ADD CONSTRAINT \`FK_d090264a2b478a21cc8f52552b9\` FOREIGN KEY (\`unlockedById\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`achievements\` DROP FOREIGN KEY \`FK_d090264a2b478a21cc8f52552b9\``);
        await queryRunner.query(`ALTER TABLE \`execution_results\` DROP FOREIGN KEY \`FK_35b26782b11673f9510ecf7a69e\``);
        await queryRunner.query(`ALTER TABLE \`learning_progress\` DROP FOREIGN KEY \`FK_c4ba35959dbdc57dde97ceb7473\``);
        await queryRunner.query(`ALTER TABLE \`learning_progress\` DROP FOREIGN KEY \`FK_2d86a96d67fe2848ec0d39560ba\``);
        await queryRunner.query(`ALTER TABLE \`learning_progress\` DROP FOREIGN KEY \`FK_ff1936e29305b9f0e52eb1fde30\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP FOREIGN KEY \`FK_acf951a58e3b9611dd96ce89042\``);
        await queryRunner.query(`ALTER TABLE \`messages\` DROP FOREIGN KEY \`FK_2db9cf2b3ca111742793f6c37ce\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP FOREIGN KEY \`FK_692a909ee0fa9383e7859f9b406\``);
        await queryRunner.query(`ALTER TABLE \`prerequisites\` DROP FOREIGN KEY \`FK_b616443e090e940951cc2fbaf94\``);
        await queryRunner.query(`ALTER TABLE \`prerequisites\` DROP FOREIGN KEY \`FK_f205de314c224ec276293924105\``);
        await queryRunner.query(`ALTER TABLE \`question_banks\` DROP FOREIGN KEY \`FK_6f408c9e6d742703af93a98083f\``);
        await queryRunner.query(`ALTER TABLE \`bank_questions\` DROP FOREIGN KEY \`FK_916010c09855614e142d71f72a2\``);
        await queryRunner.query(`ALTER TABLE \`review_schedules\` DROP FOREIGN KEY \`FK_bc8f68cc5d9a235438a767fd5a0\``);
        await queryRunner.query(`ALTER TABLE \`review_schedules\` DROP FOREIGN KEY \`FK_c76dfbe4d695e9eb548d0826c7e\``);
        await queryRunner.query(`ALTER TABLE \`submissions\` DROP FOREIGN KEY \`FK_4fc99318a291abd7e2a50f50851\``);
        await queryRunner.query(`ALTER TABLE \`submissions\` DROP FOREIGN KEY \`FK_5ddeb5fb4f6c38b0439ec52bff2\``);
        await queryRunner.query(`ALTER TABLE \`submission_answers\` DROP FOREIGN KEY \`FK_49b240a1fb2de5d9308d2125597\``);
        await queryRunner.query(`ALTER TABLE \`submission_answers\` DROP FOREIGN KEY \`FK_7e0d6cf6173772c12089cf97474\``);
        await queryRunner.query(`ALTER TABLE \`activity_questions\` DROP FOREIGN KEY \`FK_a20191ae2559a453d0bba75da9b\``);
        await queryRunner.query(`ALTER TABLE \`tutor_conversations\` DROP FOREIGN KEY \`FK_56c5533282e9ec141a9369081ca\``);
        await queryRunner.query(`ALTER TABLE \`user_affiliations\` DROP FOREIGN KEY \`FK_f6200ccffc5064f1be2e329a245\``);
        await queryRunner.query(`ALTER TABLE \`user_affiliations\` DROP FOREIGN KEY \`FK_be5b7060fa1c8a8ba2a8504e746\``);
        await queryRunner.query(`ALTER TABLE \`programs\` DROP FOREIGN KEY \`FK_82f9404fa3d1a3e1cc2c8f2d22a\``);
        await queryRunner.query(`ALTER TABLE \`enrollments\` DROP FOREIGN KEY \`FK_bf3ba3dfa95e2df7388eb4589fd\``);
        await queryRunner.query(`ALTER TABLE \`enrollments\` DROP FOREIGN KEY \`FK_470304681bce2933d3cbb680db8\``);
        await queryRunner.query(`ALTER TABLE \`classes\` DROP FOREIGN KEY \`FK_4b7ac7a7eb91f3e04229c7c0b6f\``);
        await queryRunner.query(`ALTER TABLE \`sections\` DROP FOREIGN KEY \`FK_f0881122b5efd7b004f082c084c\``);
        await queryRunner.query(`ALTER TABLE \`topics\` DROP FOREIGN KEY \`FK_36089054397b6db8da2fd67a073\``);
        await queryRunner.query(`ALTER TABLE \`learning_units\` DROP FOREIGN KEY \`FK_cb4ada233555d57c4f6e50609ad\``);
        await queryRunner.query(`ALTER TABLE \`contents\` DROP FOREIGN KEY \`FK_03bf08d52358f58f07787fc6b8f\``);
        await queryRunner.query(`ALTER TABLE \`activities\` DROP FOREIGN KEY \`FK_dc4b610a410beaee2dca89e7536\``);
        await queryRunner.query(`ALTER TABLE \`activities\` DROP FOREIGN KEY \`FK_3689e28651a4b078af91952bed8\``);
        await queryRunner.query(`ALTER TABLE \`activities\` DROP FOREIGN KEY \`FK_cc686d463a463786129e1de1cea\``);
        await queryRunner.query(`DROP INDEX \`IDX_0239ac3be75a977a71ae9cf8e0\` ON \`activity_logs\``);
        await queryRunner.query(`DROP INDEX \`IDX_8befb5d0b0f799f6b6a1af46b5\` ON \`activity_logs\``);
        await queryRunner.query(`DROP INDEX \`IDX_78666521e99d2bbe69f2ea830a\` ON \`activity_logs\``);
        await queryRunner.query(`DROP TABLE \`activity_logs\``);
        await queryRunner.query(`DROP TABLE \`achievements\``);
        await queryRunner.query(`DROP TABLE \`execution_results\``);
        await queryRunner.query(`DROP INDEX \`IDX_21d1790565894696c13f099ce9\` ON \`learning_progress\``);
        await queryRunner.query(`DROP TABLE \`learning_progress\``);
        await queryRunner.query(`DROP TABLE \`messages\``);
        await queryRunner.query(`DROP TABLE \`notifications\``);
        await queryRunner.query(`DROP INDEX \`IDX_e55545b98f91f6a5da8b004833\` ON \`prerequisites\``);
        await queryRunner.query(`DROP TABLE \`prerequisites\``);
        await queryRunner.query(`DROP TABLE \`question_banks\``);
        await queryRunner.query(`DROP TABLE \`bank_questions\``);
        await queryRunner.query(`DROP INDEX \`IDX_7e969b53fac069d54b248bf537\` ON \`review_schedules\``);
        await queryRunner.query(`DROP TABLE \`review_schedules\``);
        await queryRunner.query(`DROP INDEX \`IDX_03e1c1ddb6b33421fe8935a73f\` ON \`submissions\``);
        await queryRunner.query(`DROP INDEX \`IDX_a3a94d0cb86c82e1f221100a44\` ON \`submissions\``);
        await queryRunner.query(`DROP TABLE \`submissions\``);
        await queryRunner.query(`DROP TABLE \`submission_answers\``);
        await queryRunner.query(`DROP TABLE \`activity_questions\``);
        await queryRunner.query(`DROP INDEX \`IDX_56c5533282e9ec141a9369081c\` ON \`tutor_conversations\``);
        await queryRunner.query(`DROP TABLE \`tutor_conversations\``);
        await queryRunner.query(`DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP TABLE \`user_affiliations\``);
        await queryRunner.query(`DROP TABLE \`programs\``);
        await queryRunner.query(`DROP INDEX \`IDX_15c98649276025998cd1acaf61\` ON \`institutions\``);
        await queryRunner.query(`DROP TABLE \`institutions\``);
        await queryRunner.query(`DROP INDEX \`IDX_43599c2329cb145ee8ba57079b\` ON \`enrollments\``);
        await queryRunner.query(`DROP TABLE \`enrollments\``);
        await queryRunner.query(`DROP INDEX \`IDX_cf7491878e0fca859943862998\` ON \`classes\``);
        await queryRunner.query(`DROP INDEX \`IDX_4b7ac7a7eb91f3e04229c7c0b6\` ON \`classes\``);
        await queryRunner.query(`DROP TABLE \`classes\``);
        await queryRunner.query(`DROP INDEX \`IDX_f0881122b5efd7b004f082c084\` ON \`sections\``);
        await queryRunner.query(`DROP TABLE \`sections\``);
        await queryRunner.query(`DROP TABLE \`topics\``);
        await queryRunner.query(`DROP TABLE \`learning_units\``);
        await queryRunner.query(`DROP INDEX \`IDX_58754b2430201454bffc79cec6\` ON \`contents\``);
        await queryRunner.query(`DROP TABLE \`contents\``);
        await queryRunner.query(`DROP INDEX \`IDX_bd3144edc073063648e4efbb1f\` ON \`activities\``);
        await queryRunner.query(`DROP TABLE \`activities\``);
        await queryRunner.query(`DROP INDEX \`IDX_ce7823da2e27674fbd0392e867\` ON \`activity_types\``);
        await queryRunner.query(`DROP TABLE \`activity_types\``);
    }

}
